function getRandomIndex(listLength) {
  return Math.floor(Math.random() * (listLength - 1))
}

export function getDescriptiveAnimal() {
  const adjectives = [
    { english: 'Amazing', chinese: '令人惊叹的' },
    { english: 'Awesome', chinese: '了不起的' },
    { english: 'Adventurous', chinese: '冒险的' },
    { english: 'Ambitious', chinese: '有雄心的' },
    { english: 'Adorable', chinese: '可爱的' },
    { english: 'Artistic', chinese: '艺术的' },
    { english: 'Agile', chinese: '敏捷的' },
    { english: 'Acrobatic', chinese: '杂技的' },
    { english: 'Astonishing', chinese: '惊人的' },
    { english: 'Authentic', chinese: '真实的' },
    { english: 'Awkward', chinese: '笨拙的' },
    { english: 'Ancient', chinese: '古老的' },
    { english: 'Brave', chinese: '勇敢的' },
    { english: 'Beautiful', chinese: '美丽的' },
    { english: 'Bright', chinese: '明亮的' },
    { english: 'Busy', chinese: '忙碌的' },
    { english: 'Big', chinese: '大的' },
    { english: 'Bold', chinese: '大胆的' },
    { english: 'Blue', chinese: '蓝色的' },
    { english: 'Basic', chinese: '基本的' },
    { english: 'Blissful', chinese: '幸福的' },
    { english: 'Bouncy', chinese: '有弹性的' },
    { english: 'Bashful', chinese: '害羞的' },
    { english: 'Creative', chinese: '有创造力的' },
    { english: 'Confident', chinese: '自信的' },
    { english: 'Cheerful', chinese: '快乐的' },
    { english: 'Calm', chinese: '平静的' },
    { english: 'Cute', chinese: '可爱的' },
    { english: 'Clever', chinese: '聪明的' },
    { english: 'Curious', chinese: '好奇的' },
    { english: 'Charming', chinese: '迷人的' },
    { english: 'Courageous', chinese: '勇敢的' },
    { english: 'Cool', chinese: '酷的' },
    { english: 'Considerate', chinese: '体贴的' },
    { english: 'Caring', chinese: '关心的' },
    { english: 'Crazy', chinese: '疯狂的' },
    { english: 'Classic', chinese: '经典的' },
    { english: 'Delightful', chinese: '令人愉快的' },
    { english: 'Dreamy', chinese: '梦幻的' },
    { english: 'Daring', chinese: '大胆的' },
    { english: 'Decent', chinese: '正派的' },
    { english: 'Defiant', chinese: '挑衅的' },
    { english: 'Dedicated', chinese: '专注的' },
    { english: 'Dramatic', chinese: '戏剧性的' },
    { english: 'Dizzy', chinese: '头晕的' },
    { english: 'Demanding', chinese: '苛刻的' },
    { english: 'Diligent', chinese: '勤奋的' },
    { english: 'Dazzling', chinese: '耀眼的' },
    { english: 'Elegant', chinese: '优雅的' },
    { english: 'Enthusiastic', chinese: '热情的' },
    { english: 'Eager', chinese: '渴望的' },
    { english: 'Efficient', chinese: '高效的' },
    { english: 'Empathetic', chinese: '有同理心的' },
    { english: 'Entertaining', chinese: '有趣的' },
    { english: 'Expressive', chinese: '富有表现力的' },
    { english: 'Elderly', chinese: '年老的' },
    { english: 'Fantastic', chinese: '极好的' },
    { english: 'Fabulous', chinese: '极好的' },
    { english: 'Friendly', chinese: '友好的' },
    { english: 'Funny', chinese: '有趣的' },
    { english: 'Fearless', chinese: '无畏的' },
    { english: 'Fluffy', chinese: '毛茸茸的' },
    { english: 'Fierce', chinese: '凶猛的' },
    { english: 'Frugal', chinese: '节俭的' },
    { english: 'Fast', chinese: '快的' },
    { english: 'Famous', chinese: '著名的' },
    { english: 'Gorgeous', chinese: '华丽的' },
    { english: 'Gentle', chinese: '温柔的' },
    { english: 'Generous', chinese: '慷慨的' },
    { english: 'Gracious', chinese: '亲切的' },
    { english: 'Glorious', chinese: '光荣的' },
    { english: 'Graceful', chinese: '优雅的' },
    { english: 'Groovy', chinese: '时髦的' },
    { english: 'Grumpy', chinese: '脾气暴躁的' },
    { english: 'Gigantic', chinese: '巨大的' },
    { english: 'Happy', chinese: '快乐的' },
    { english: 'Humble', chinese: '谦逊的' },
    { english: 'Honest', chinese: '诚实的' },
    { english: 'Healthy', chinese: '健康的' },
    { english: 'Heavy', chinese: '重的' },
    { english: 'Helpful', chinese: '有帮助的' },
    { english: 'Hilarious', chinese: '滑稽的' },
    { english: 'Hardworking', chinese: '勤奋的' },
    { english: 'Hungry', chinese: '饥饿的' },
    { english: 'Interesting', chinese: '有趣的' },
    { english: 'Intelligent', chinese: '聪明的' },
    { english: 'Inspiring', chinese: '鼓舞人心的' },
    { english: 'Imaginative', chinese: '富有想象力的' },
    { english: 'Inquisitive', chinese: '好奇的' },
    { english: 'Industrious', chinese: '勤劳的' },
    { english: 'Idealistic', chinese: '理想主义的' },
    { english: 'Icy', chinese: '冰冷的' },
    { english: 'Joyful', chinese: '快乐的' },
    { english: 'Jolly', chinese: '欢乐的' },
    { english: 'Jaunty', chinese: '活泼的' },
    { english: 'Jumpy', chinese: '跳跃的' },
    { english: 'Judgmental', chinese: '爱评判的' },
    { english: 'Jittery', chinese: '紧张不安的' },
    { english: 'Jubilant', chinese: '欢欣的' },
    { english: 'Kind', chinese: '善良的' },
    { english: 'Knowledgeable', chinese: '知识渊博的' },
    { english: 'Keen', chinese: '热切的' },
    { english: 'Kooky', chinese: '古怪的' },
    { english: 'Loud', chinese: '大声的' },
    { english: 'Lively', chinese: '活泼的' },
    { english: 'Lazy', chinese: '懒惰的' },
    { english: 'Loyal', chinese: '忠诚的' },
    { english: 'Lucky', chinese: '幸运的' },
    { english: 'Mysterious', chinese: '神秘的' },
    { english: 'Moody', chinese: '喜怒无常的' },
    { english: 'Mindful', chinese: '留心的' },
    { english: 'Mischievous', chinese: '调皮的' },
    { english: 'Modest', chinese: '谦虚的' },
    { english: 'Magical', chinese: '神奇的' },
    { english: 'Nervous', chinese: '紧张的' },
    { english: 'Noble', chinese: '高贵的' },
    { english: 'Nonchalant', chinese: '冷淡的' },
    { english: 'Noisy', chinese: '嘈杂的' },
    { english: 'Needy', chinese: '贫困的' },
    { english: 'Optimistic', chinese: '乐观的' },
    { english: 'Observant', chinese: '善于观察的' },
    { english: 'Obedient', chinese: '听话的' },
    { english: 'Offensive', chinese: '冒犯的' },
    { english: 'Patient', chinese: '耐心的' },
    { english: 'Positive', chinese: '积极的' },
    { english: 'Powerful', chinese: '强大的' },
    { english: 'Popular', chinese: '受欢迎的' },
    { english: 'Polite', chinese: '有礼貌的' },
    { english: 'Peaceful', chinese: '和平的' },
    { english: 'Playful', chinese: '爱玩的' },
    { english: 'Pleasant', chinese: '愉快的' },
    { english: 'Practical', chinese: '实际的' },
    { english: 'Proud', chinese: '骄傲的' },
    { english: 'Puzzled', chinese: '困惑的' },
    { english: 'Persistent', chinese: '坚持不懈的' },
    { english: 'Passionate', chinese: '热情的' },
    { english: 'Quaint', chinese: '古雅的' },
    { english: 'Quick', chinese: '快的' },
    { english: 'Quiet', chinese: '安静的' },
    { english: 'Quirky', chinese: '古怪的' },
    { english: 'Reliable', chinese: '可靠的' },
    { english: 'Responsible', chinese: '负责任的' },
    { english: 'Rich', chinese: '富有的' },
    { english: 'Rude', chinese: '粗鲁的' },
    { english: 'Respectful', chinese: '尊重的' },
    { english: 'Rational', chinese: '理性的' },
    { english: 'Rustic', chinese: '乡村的' },
    { english: 'Reckless', chinese: '鲁莽的' },
    { english: 'Rambunctious', chinese: '喧闹的' },
    { english: 'Strong', chinese: '强壮的' },
    { english: 'Smart', chinese: '聪明的' },
    { english: 'Serious', chinese: '严肃的' },
    { english: 'Sad', chinese: '悲伤的' },
    { english: 'Simple', chinese: '简单的' },
    { english: 'Sincere', chinese: '真诚的' },
    { english: 'Sweet', chinese: '甜美的' },
    { english: 'Shy', chinese: '害羞的' },
    { english: 'Successful', chinese: '成功的' },
    { english: 'Surprised', chinese: '惊讶的' },
    { english: 'Tall', chinese: '高的' },
    { english: 'Talkative', chinese: '健谈的' },
    { english: 'Thoughtful', chinese: '体贴的' },
    { english: 'Thrifty', chinese: '节俭的' },
    { english: 'Trustworthy', chinese: '值得信赖的' },
    { english: 'Tenacious', chinese: '顽强的' },
    { english: 'Tiny', chinese: '微小的' },
    { english: 'Tired', chinese: '疲倦的' },
    { english: 'Unique', chinese: '独特的' },
    { english: 'Unusual', chinese: '不寻常的' },
    { english: 'Useless', chinese: '无用的' },
    { english: 'Witty', chinese: '机智的' },
    { english: 'Wise', chinese: '明智的' },
    { english: 'Wicked', chinese: '邪恶的' },
    { english: 'Wary', chinese: '谨慎的' },
    { english: 'Wholesome', chinese: '健康的' },
    { english: 'Young', chinese: '年轻的' },
    { english: 'Zealous', chinese: '热心的' },
  ]

  const animals = [
    { english: 'Alligator', chinese: '短吻鳄' },
    { english: 'Alpaca', chinese: '羊驼' },
    { english: 'Antelope', chinese: '羚羊' },
    { english: 'Ape', chinese: '猿' },
    { english: 'Armadillo', chinese: '犰狳' },
    { english: 'Badger', chinese: '獾' },
    { english: 'Bear', chinese: '熊' },
    { english: 'Beaver', chinese: '海狸' },
    { english: 'Bee', chinese: '蜜蜂' },
    { english: 'Bird', chinese: '鸟' },
    { english: 'Bison', chinese: '野牛' },
    { english: 'Buffalo', chinese: '水牛' },
    { english: 'Boar', chinese: '野猪' },
    { english: 'Butterfly', chinese: '蝴蝶' },
    { english: 'Camel', chinese: '骆驼' },
    { english: 'Cat', chinese: '猫' },
    { english: 'Cheetah', chinese: '猎豹' },
    { english: 'Chicken', chinese: '鸡' },
    { english: 'Clam', chinese: '蛤蜊' },
    { english: 'Coyote', chinese: '土狼' },
    { english: 'Crane', chinese: '鹤' },
    { english: 'Crow', chinese: '乌鸦' },
    { english: 'Deer', chinese: '鹿' },
    { english: 'Dinosaur', chinese: '恐龙' },
    { english: 'Dog', chinese: '狗' },
    { english: 'Dolphin', chinese: '海豚' },
    { english: 'Donkey', chinese: '驴' },
    { english: 'Dove', chinese: '鸽子' },
    { english: 'Duck', chinese: '鸭子' },
    { english: 'Eagle', chinese: '鹰' },
    { english: 'Echidna', chinese: '针鼹' },
    { english: 'Elephant', chinese: '大象' },
    { english: 'Elk', chinese: '麋鹿' },
    { english: 'Falcon', chinese: '猎鹰' },
    { english: 'Ferret', chinese: '雪貂' },
    { english: 'Fish', chinese: '鱼' },
    { english: 'Finch', chinese: '雀' },
    { english: 'Fox', chinese: '狐狸' },
    { english: 'Frog', chinese: '青蛙' },
    { english: 'Gerbil', chinese: '沙鼠' },
    { english: 'Giraffe', chinese: '长颈鹿' },
    { english: 'Goat', chinese: '山羊' },
    { english: 'Goose', chinese: '鹅' },
    { english: 'Gorilla', chinese: '大猩猩' },
    { english: 'Grasshopper', chinese: '蚱蜢' },
    { english: 'Gull', chinese: '海鸥' },
    { english: 'Hamster', chinese: '仓鼠' },
    { english: 'Hare', chinese: '野兔' },
    { english: 'Hawk', chinese: '鹰' },
    { english: 'Hedgehog', chinese: '刺猬' },
    { english: 'Heron', chinese: '苍鹭' },
    { english: 'Hippopotamus', chinese: '河马' },
    { english: 'Hornet', chinese: '大黄蜂' },
    { english: 'Horse', chinese: '马' },
    { english: 'Hummingbird', chinese: '蜂鸟' },
    { english: 'Hyena', chinese: '鬣狗' },
    { english: 'Jellyfish', chinese: '水母' },
    { english: 'Kangaroo', chinese: '袋鼠' },
    { english: 'Koala', chinese: '考拉' },
    { english: 'Lark', chinese: '云雀' },
    { english: 'Leopard', chinese: '豹' },
    { english: 'Lion', chinese: '狮子' },
    { english: 'Llama', chinese: '美洲驼' },
    { english: 'Mallard', chinese: '绿头鸭' },
    { english: 'Mole', chinese: '鼹鼠' },
    { english: 'Monkey', chinese: '猴子' },
    { english: 'Moose', chinese: '驼鹿' },
    { english: 'Mule', chinese: '骡子' },
    { english: 'Opossum', chinese: '负鼠' },
    { english: 'Orca', chinese: '虎鲸' },
    { english: 'Ostrich', chinese: '鸵鸟' },
    { english: 'Otter', chinese: '水獭' },
    { english: 'Owl', chinese: '猫头鹰' },
    { english: 'Ox', chinese: '公牛' },
    { english: 'Oyster', chinese: '牡蛎' },
    { english: 'Panda', chinese: '熊猫' },
    { english: 'Parrot', chinese: '鹦鹉' },
    { english: 'Penguin', chinese: '企鹅' },
    { english: 'Pheasant', chinese: '野鸡' },
    { english: 'Pig', chinese: '猪' },
    { english: 'Pigeon', chinese: '鸽子' },
    { english: 'Platypus', chinese: '鸭嘴兽' },
    { english: 'Porpoise', chinese: '鼠海豚' },
    { english: 'Quail', chinese: '鹌鹑' },
    { english: 'Rabbit', chinese: '兔子' },
    { english: 'Raccoon', chinese: '浣熊' },
    { english: 'Raven', chinese: '乌鸦' },
    { english: 'Rhino', chinese: '犀牛' },
    { english: 'Seal', chinese: '海豹' },
    { english: 'Shark', chinese: '鲨鱼' },
    { english: 'Sheep', chinese: '羊' },
    { english: 'Skunk', chinese: '臭鼬' },
    { english: 'Squirrel', chinese: '松鼠' },
    { english: 'Swallow', chinese: '燕子' },
    { english: 'Swan', chinese: '天鹅' },
    { english: 'Tiger', chinese: '老虎' },
    { english: 'Toad', chinese: '蟾蜍' },
    { english: 'Turkey', chinese: '火鸡' },
    { english: 'Turtle', chinese: '海龟' },
    { english: 'Walrus', chinese: '海象' },
    { english: 'Wasp', chinese: '黄蜂' },
    { english: 'Weasel', chinese: '黄鼠狼' },
    { english: 'Whale', chinese: '鲸鱼' },
    { english: 'Wolf', chinese: '狼' },
    { english: 'Wombat', chinese: '袋熊' },
    { english: 'Woodpecker', chinese: '啄木鸟' },
    { english: 'Yak', chinese: '牦牛' },
    { english: 'Zebra', chinese: '斑马' },
  ]
  const chosenAdjective = adjectives[getRandomIndex(adjectives.length)]
  const chosenAnimal = animals[getRandomIndex(animals.length)]
  return {
    english: [chosenAdjective['english'], chosenAnimal['english']],
    chinese: [chosenAdjective['chinese'], chosenAnimal['chinese']],
  }
}

export function getRandomString() {
  const upperCaseLetters = [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
  ]

  const chosenString = upperCaseLetters[getRandomIndex(upperCaseLetters.length)]
  return [chosenString]
}
